name: CI/CD Pipeline to GCP Cloud Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run automated tests
      run: |
        export PYTHONPATH=.
        pytest tests/

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker to use Artifact Registry
      run: gcloud auth configure-docker asia-southeast2-docker.pkg.dev

    - name: Build and Push Docker Image to Artifact Registry
      env:
        GCP_PROJECT_ID: sentimentanalyzer25
        GCP_REGION: asia-southeast2

        GCP_ARTIFACT_REGISTRY_REPO: default
        IMAGE_NAME: new_image
        # asia-southeast2-docker.pkg.dev/sentimentanalyzer25/default
        IMAGE_FULL_PATH: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_ARTIFACT_REGISTRY_REPO }}/${{ env.IMAGE_NAME }}
        IMAGE_TAG: ${{ github.sha }}

      run: |
        docker build -t $IMAGE_FULL_PATH:$IMAGE_TAG .
        docker push $IMAGE_FULL_PATH:$IMAGE_TAG

    - name: Deploy to Cloud Run
      env:
        GCP_PROJECT_ID: sentimentanalyzer25
        GCP_REGION: asia-southeast2
        SERVICE_NAME: sentiment-analyzer-service
        IMAGE_TO_DEPLOY: ${{ env.IMAGE_FULL_PATH }}:${{ env.IMAGE_TAG }}

      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image ${{ env.IMAGE_TO_DEPLOY }} \
          --region ${{ env.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated